#!/bin/sh

echo "Running TypeScript type check..."
npm run typecheck

if [ $? -ne 0 ]; then
    echo "TypeScript type check failed. Push aborted."
    exit 1
fi

echo "Running tests..."
#npm run test:run

if [ $? -ne 0 ]; then
    echo "Tests failed. Push aborted."
    exit 1
fi

echo "Pre-push checks passed."